// Mocks generated by Mockito 5.0.9 from annotations
// in flutter_mockito_di_unit_test/test/repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_mockito_di_unit_test/api_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> get(String? endpoint) =>
      (super.noSuchMethod(Invocation.method(#get, [endpoint]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<String> post(String? endpoint, {String? body}) =>
      (super.noSuchMethod(Invocation.method(#post, [endpoint], {#body: body}),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<String> put(String? endpoint, {String? body}) =>
      (super.noSuchMethod(Invocation.method(#put, [endpoint], {#body: body}),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<String> delete(String? endpoint) =>
      (super.noSuchMethod(Invocation.method(#delete, [endpoint]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
